/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbcali.overlappingCommunitiesViewer.GUI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CamiloDelgado
 */
public class OgvGeneratorPanel extends javax.swing.JPanel {

    private File fileTags;
    private File fileCommunities;
    private File fileRelations;
    
    /**
     * Creates new form OgvGeneratorPanel
     */
    public OgvGeneratorPanel() {
        initComponents();
    }

    public File getFileTags() {
        return fileTags;
    }

    public File getFileCommunities() {
        return fileCommunities;
    }

    public File getFileRelations() {
        return fileRelations;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectFiles = new javax.swing.JLabel();
        lblFileTags = new javax.swing.JLabel();
        lblFileRelations = new javax.swing.JLabel();
        lblFileCommunities = new javax.swing.JLabel();
        lblTags = new javax.swing.JLabel();
        lblRelations = new javax.swing.JLabel();
        lblCommunities = new javax.swing.JLabel();
        btnSelectTags = new javax.swing.JButton();
        btnSelectRelations = new javax.swing.JButton();
        btnSelectCommunities = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(lblSelectFiles, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblSelectFiles.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblFileTags, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblFileTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblFileRelations, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblFileRelations.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblFileCommunities, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblFileCommunities.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblTags, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelations, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblRelations.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCommunities, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.lblCommunities.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnSelectTags, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.btnSelectTags.text")); // NOI18N
        btnSelectTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectTagsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnSelectRelations, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.btnSelectRelations.text")); // NOI18N
        btnSelectRelations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectRelationsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnSelectCommunities, org.openide.util.NbBundle.getMessage(OgvGeneratorPanel.class, "OgvGeneratorPanel.btnSelectCommunities.text")); // NOI18N
        btnSelectCommunities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCommunitiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTags)
                            .addComponent(lblFileTags, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectTags))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFileRelations, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRelations))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectRelations))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectFiles)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFileCommunities, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCommunities))
                                .addGap(18, 18, 18)
                                .addComponent(btnSelectCommunities)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTags)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFileTags))
                            .addComponent(btnSelectTags, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(lblRelations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFileRelations))
                    .addComponent(btnSelectRelations, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCommunities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFileCommunities)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectCommunities, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectTagsActionPerformed
        File tags = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.setFileFilter(new FileNameExtensionFilter("Txt File", "txt"));        
        
        jf.showOpenDialog(this);
        tags = jf.getSelectedFile();
        
        if (tags != null && tags.exists()) {
            String name = tags.getName();
            String extension = name.substring(name.lastIndexOf("."));
            if(extension.equalsIgnoreCase(".txt")){
                fileTags = tags;
                lblFileTags.setText(name);
            }else{
                JOptionPane.showMessageDialog(null, "El formato del archivo no es 'txt'", "File Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectTagsActionPerformed

    private void btnSelectRelationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectRelationsActionPerformed
        File relations = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.setFileFilter(new FileNameExtensionFilter("Txt File", "txt"));        
        
        jf.showOpenDialog(this);
        relations = jf.getSelectedFile();
        
        if (relations != null && relations.exists()) {
            String name = relations.getName();
            String extension = name.substring(name.lastIndexOf("."));
            if(extension.equalsIgnoreCase(".txt")){
                fileRelations = relations;
                lblFileRelations.setText(name);
            }else{
                JOptionPane.showMessageDialog(null, "El formato del archivo no es 'txt'", "File Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectRelationsActionPerformed

    private void btnSelectCommunitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCommunitiesActionPerformed
        File communities = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jf.setFileFilter(new FileNameExtensionFilter("Txt File", "txt"));        
        
        jf.showOpenDialog(this);
        communities = jf.getSelectedFile();
        
        System.out.println(communities);
        
        if (communities != null && communities.exists()) {
            String name = communities.getName();
            String extension = name.substring(name.lastIndexOf("."));
            if(extension.equalsIgnoreCase(".txt")){
                fileCommunities = communities;
                lblFileCommunities.setText(name);
            }else{
                JOptionPane.showMessageDialog(null, "El formato del archivo no es 'txt'", "File Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectCommunitiesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectCommunities;
    private javax.swing.JButton btnSelectRelations;
    private javax.swing.JButton btnSelectTags;
    private javax.swing.JLabel lblCommunities;
    private javax.swing.JLabel lblFileCommunities;
    private javax.swing.JLabel lblFileRelations;
    private javax.swing.JLabel lblFileTags;
    private javax.swing.JLabel lblRelations;
    private javax.swing.JLabel lblSelectFiles;
    private javax.swing.JLabel lblTags;
    // End of variables declaration//GEN-END:variables
}
