/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbcali.overlappingCommunitiesViewer.GUI;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author zinko
 */
public class PCArchivos extends javax.swing.JPanel {

    List<File> files = new ArrayList<>();
    /**
     * Creates new form PCArchivos
     */
    public PCArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTags = new javax.swing.JButton();
        btnRelaciones = new javax.swing.JButton();
        btnComunidades = new javax.swing.JButton();
        btnCrearGrafo = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(btnTags, org.openide.util.NbBundle.getMessage(PCArchivos.class, "PCArchivos.btnTags.text")); // NOI18N
        btnTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnRelaciones, org.openide.util.NbBundle.getMessage(PCArchivos.class, "PCArchivos.btnRelaciones.text")); // NOI18N
        btnRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnComunidades, org.openide.util.NbBundle.getMessage(PCArchivos.class, "PCArchivos.btnComunidades.text")); // NOI18N
        btnComunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComunidadesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCrearGrafo, org.openide.util.NbBundle.getMessage(PCArchivos.class, "PCArchivos.btnCrearGrafo.text")); // NOI18N
        btnCrearGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTags)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelaciones)
                        .addGap(18, 18, 18)
                        .addComponent(btnComunidades)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTags)
                    .addComponent(btnRelaciones)
                    .addComponent(btnComunidades))
                .addGap(18, 18, 18)
                .addComponent(btnCrearGrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagsActionPerformed
        File tags = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (!jf.isMultiSelectionEnabled()) {
            jf.setMultiSelectionEnabled(true);
        }
        jf.showOpenDialog(this);
        tags = jf.getSelectedFile();
        files.add(tags);
    }//GEN-LAST:event_btnTagsActionPerformed

    private void btnRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionesActionPerformed
        File relaciones = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (!jf.isMultiSelectionEnabled()) {
            jf.setMultiSelectionEnabled(true);
        }
        jf.showOpenDialog(this);
        relaciones = jf.getSelectedFile();
        files.add(relaciones);
    }//GEN-LAST:event_btnRelacionesActionPerformed

    private void btnComunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComunidadesActionPerformed
        File comunidades = null;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (!jf.isMultiSelectionEnabled()) {
            jf.setMultiSelectionEnabled(true);
        }
        jf.showOpenDialog(this);
        comunidades = jf.getSelectedFile();
        files.add(comunidades);
    }//GEN-LAST:event_btnComunidadesActionPerformed

    private void btnCrearGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGrafoActionPerformed
        UGVPanel ugv = new UGVPanel();
        ugv.setVisible(true);
    }//GEN-LAST:event_btnCrearGrafoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComunidades;
    private javax.swing.JButton btnCrearGrafo;
    private javax.swing.JButton btnRelaciones;
    private javax.swing.JButton btnTags;
    // End of variables declaration//GEN-END:variables
}
