/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbcali.overlappingCommunitiesViewer.filter;

import co.edu.usbcali.overlappingCommunitiesViewer.generator.model.FiltersValues;
import co.edu.usbcali.overlappingCommunitiesViewer.generator.model.OptionsFilter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author zinko
 */
public class OcvFilterUI extends javax.swing.JPanel{

    private OcvFilterCustom filter;
    OptionsFilter optionsFilter = new OptionsFilter();
    OptionsFilter optionsFilterEdge = new OptionsFilter();
    
    /**
     * Creates new form OcvFilterNode
     */
    public OcvFilterUI() {
        initComponents();
    }

    public void setup(OcvFilterCustom f) {
        this.filter = f;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JTabbedPane();
        pnlNodos = new javax.swing.JPanel();
        lblConTags = new javax.swing.JLabel();
        txtConTags = new javax.swing.JTextField();
        lblSinTags = new javax.swing.JLabel();
        txtSinTags = new javax.swing.JTextField();
        lblMasComunidades = new javax.swing.JLabel();
        lblMenosComunidades = new javax.swing.JLabel();
        txtMasComunidades = new javax.swing.JTextField();
        txtMenosComunidades = new javax.swing.JTextField();
        pnlAristas = new javax.swing.JPanel();
        lblMasPeso = new javax.swing.JLabel();
        lblMenosPeso = new javax.swing.JLabel();
        txtMasPeso = new javax.swing.JTextField();
        txtMenosPeso = new javax.swing.JTextField();
        btnFiltros = new javax.swing.JButton();
        btnCleanFiltros = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(lblConTags, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblConTags.text")); // NOI18N

        txtConTags.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtConTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSinTags, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblSinTags.text")); // NOI18N

        txtSinTags.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtSinTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMasComunidades, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMasComunidades.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMenosComunidades, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMenosComunidades.text")); // NOI18N

        txtMasComunidades.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMasComunidades.text")); // NOI18N
        txtMasComunidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMasComunidadesKeyTyped(evt);
            }
        });

        txtMenosComunidades.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMenosComunidades.text")); // NOI18N
        txtMenosComunidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMenosComunidadesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlNodosLayout = new javax.swing.GroupLayout(pnlNodos);
        pnlNodos.setLayout(pnlNodosLayout);
        pnlNodosLayout.setHorizontalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConTags)
                    .addComponent(lblSinTags)
                    .addComponent(lblMasComunidades)
                    .addComponent(lblMenosComunidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMenosComunidades, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtMasComunidades)
                    .addComponent(txtConTags)
                    .addComponent(txtSinTags))
                .addContainerGap())
        );
        pnlNodosLayout.setVerticalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConTags))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSinTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSinTags))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasComunidades))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenosComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenosComunidades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFiltros.addTab(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.pnlNodos.TabConstraints.tabTitle"), pnlNodos); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMasPeso, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMasPeso.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMenosPeso, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMenosPeso.text")); // NOI18N

        txtMasPeso.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMasPeso.text")); // NOI18N
        txtMasPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMasPesoKeyTyped(evt);
            }
        });

        txtMenosPeso.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMenosPeso.text")); // NOI18N
        txtMenosPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMenosPesoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlAristasLayout = new javax.swing.GroupLayout(pnlAristas);
        pnlAristas.setLayout(pnlAristasLayout);
        pnlAristasLayout.setHorizontalGroup(
            pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAristasLayout.createSequentialGroup()
                        .addComponent(lblMenosPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(txtMenosPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAristasLayout.createSequentialGroup()
                        .addComponent(lblMasPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMasPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAristasLayout.setVerticalGroup(
            pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasPeso))
                .addGap(18, 18, 18)
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenosPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenosPeso))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pnlFiltros.addTab(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.pnlAristas.TabConstraints.tabTitle"), pnlAristas); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnFiltros, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.btnFiltros.text")); // NOI18N
        btnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrosActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCleanFiltros, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.btnCleanFiltros.text")); // NOI18N
        btnCleanFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCleanFiltros)
                .addGap(18, 18, 18)
                .addComponent(btnFiltros)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltros)
                    .addComponent(btnCleanFiltros))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMasComunidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasComunidadesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMasComunidadesKeyTyped

    private void txtMenosComunidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenosComunidadesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMenosComunidadesKeyTyped

    private void txtMasPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasPesoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && 
                (c != '.' || txtMasPeso.getText().contains(".")) ) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMasPesoKeyTyped

    private void txtMenosPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenosPesoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && 
                (c != '.' || txtMenosPeso.getText().contains(".")) ) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMenosPesoKeyTyped

    private void btnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrosActionPerformed
        List<FiltersValues> filtroNodos = validarFiltrosNodos();
        List<FiltersValues> filtroAristas = validarFiltrosAristas();
    
        if(filtroNodos.isEmpty() && filtroAristas.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay filtros por aplicar", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            filter.setNodesFilter(filtroNodos);
            filter.setAristasFilter(filtroAristas);
            filter.setOptionsFilter(optionsFilter);
            filter.setOptionsFilterEdge(optionsFilterEdge);
        }
    }//GEN-LAST:event_btnFiltrosActionPerformed

    private void btnCleanFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanFiltrosActionPerformed
        txtConTags.setText("");
        txtSinTags.setText("");
        txtMasComunidades.setText("");
        txtMenosComunidades.setText("");
        
        txtMasPeso.setText("");
        txtMenosPeso.setText("");
    }//GEN-LAST:event_btnCleanFiltrosActionPerformed
    
    public List<FiltersValues> validarFiltrosNodos(){
        
        List<FiltersValues> cfilters = new ArrayList<>();
        //Nodos
        String conTags = txtConTags.getText();
        String sinTags = txtSinTags.getText();
        String masComunidades = txtMasComunidades.getText();
        String menosComunidades = txtMenosComunidades.getText();
        
        
        if(!conTags.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(0);
            cf.setValue(conTags);
            cfilters.add(cf);
            optionsFilter.setOption1(1);
        }else if(conTags.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(4);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilter.setOption1(0);
        }
        if(!sinTags.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(1);
            cf.setValue(sinTags);
            cfilters.add(cf);
            optionsFilter.setOption2(1);
        }else if(sinTags.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(4);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilter.setOption2(0);
        }
        if(!masComunidades.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(2);
            cf.setValue(masComunidades);
            cfilters.add(cf);
            optionsFilter.setOption3(1);
        }else if(masComunidades.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(4);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilter.setOption3(0);
        }
        if(!menosComunidades.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(3);
            cf.setValue(menosComunidades);
            cfilters.add(cf);
            optionsFilter.setOption4(1);
        }else if(menosComunidades.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(4);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilter.setOption4(0);
        }
        return cfilters;
    }
    
    public List<FiltersValues> validarFiltrosAristas(){
        
        List<FiltersValues> cfilters = new ArrayList<>();
        
        //Aristas
        String pesoMayor = txtMasPeso.getText();
        String pesoMenor = txtMenosPeso.getText();
        
        if(!pesoMayor.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(0);
            cf.setValue(pesoMayor);
            cfilters.add(cf);
            optionsFilterEdge.setOption1(1);
        }else if(pesoMayor.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(2);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilterEdge.setOption1(0);
        }
        if(!pesoMenor.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(1);
            cf.setValue(pesoMenor);
            cfilters.add(cf);
            optionsFilterEdge.setOption2(1);
        }else if(pesoMenor.equals("")){
            FiltersValues cf = new FiltersValues();
            cf.setId(3);
            cf.setValue("NOT VALUE");
            cfilters.add(cf);
            optionsFilterEdge.setOption2(0);
        }
        return cfilters;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanFiltros;
    private javax.swing.JButton btnFiltros;
    private javax.swing.JLabel lblConTags;
    private javax.swing.JLabel lblMasComunidades;
    private javax.swing.JLabel lblMasPeso;
    private javax.swing.JLabel lblMenosComunidades;
    private javax.swing.JLabel lblMenosPeso;
    private javax.swing.JLabel lblSinTags;
    private javax.swing.JPanel pnlAristas;
    private javax.swing.JTabbedPane pnlFiltros;
    private javax.swing.JPanel pnlNodos;
    private javax.swing.JTextField txtConTags;
    private javax.swing.JTextField txtMasComunidades;
    private javax.swing.JTextField txtMasPeso;
    private javax.swing.JTextField txtMenosComunidades;
    private javax.swing.JTextField txtMenosPeso;
    private javax.swing.JTextField txtSinTags;
    // End of variables declaration//GEN-END:variables

}
