/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbcali.overlappingCommunitiesViewer.filter;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.gephi.filters.spi.FilterProperty;
import org.openide.util.WeakListeners;

/**
 *
 * @author zinko
 */
public class OcvFilterUI extends javax.swing.JPanel implements ChangeListener{

    private OcvFilterCustom filter;
    
    /**
     * Creates new form OcvFilterNode
     */
    public OcvFilterUI() {
        initComponents();
    }

    public void setup(OcvFilterCustom f) {
        this.filter = f;        
    }
    
    @Override
    public void stateChanged(ChangeEvent e) {
        //The property number 1 is the top property
        FilterProperty top = filter.getProperties()[1];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JTabbedPane();
        pnlComunidades = new javax.swing.JPanel();
        lblMasNodos = new javax.swing.JLabel();
        txtMasNodos = new javax.swing.JTextField();
        lblMenosNodos = new javax.swing.JLabel();
        txtMenosNodos = new javax.swing.JTextField();
        pnlNodos = new javax.swing.JPanel();
        lblConTags = new javax.swing.JLabel();
        txtConTags = new javax.swing.JTextField();
        lblSinTags = new javax.swing.JLabel();
        txtSinTags = new javax.swing.JTextField();
        lblMasComunidades = new javax.swing.JLabel();
        lblMenosComunidades = new javax.swing.JLabel();
        txtMasComunidades = new javax.swing.JTextField();
        txtMenosComunidades = new javax.swing.JTextField();
        pnlAristas = new javax.swing.JPanel();
        lblMasPeso = new javax.swing.JLabel();
        lblMenosPeso = new javax.swing.JLabel();
        txtMasPeso = new javax.swing.JTextField();
        txtMenosPeso = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(lblMasNodos, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMasNodos.text")); // NOI18N

        txtMasNodos.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMasNodos.text")); // NOI18N
        txtMasNodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMasNodosKeyTyped(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblMenosNodos, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMenosNodos.text")); // NOI18N

        txtMenosNodos.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMenosNodos.text")); // NOI18N
        txtMenosNodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMenosNodosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlComunidadesLayout = new javax.swing.GroupLayout(pnlComunidades);
        pnlComunidades.setLayout(pnlComunidadesLayout);
        pnlComunidadesLayout.setHorizontalGroup(
            pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComunidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMasNodos)
                    .addComponent(lblMenosNodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMasNodos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtMenosNodos))
                .addContainerGap())
        );
        pnlComunidadesLayout.setVerticalGroup(
            pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComunidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasNodos))
                .addGap(18, 18, 18)
                .addGroup(pnlComunidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenosNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenosNodos))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pnlFiltros.addTab(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.pnlComunidades.TabConstraints.tabTitle"), pnlComunidades); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblConTags, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblConTags.text")); // NOI18N

        txtConTags.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtConTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSinTags, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblSinTags.text")); // NOI18N

        txtSinTags.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtSinTags.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMasComunidades, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMasComunidades.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMenosComunidades, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMenosComunidades.text")); // NOI18N

        txtMasComunidades.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMasComunidades.text")); // NOI18N
        txtMasComunidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMasComunidadesKeyTyped(evt);
            }
        });

        txtMenosComunidades.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMenosComunidades.text")); // NOI18N
        txtMenosComunidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMenosComunidadesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlNodosLayout = new javax.swing.GroupLayout(pnlNodos);
        pnlNodos.setLayout(pnlNodosLayout);
        pnlNodosLayout.setHorizontalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConTags)
                    .addComponent(lblSinTags)
                    .addComponent(lblMasComunidades)
                    .addComponent(lblMenosComunidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMenosComunidades, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtMasComunidades)
                    .addComponent(txtConTags)
                    .addComponent(txtSinTags))
                .addContainerGap())
        );
        pnlNodosLayout.setVerticalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConTags))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSinTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSinTags))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasComunidades))
                .addGap(18, 18, 18)
                .addGroup(pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenosComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenosComunidades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFiltros.addTab(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.pnlNodos.TabConstraints.tabTitle"), pnlNodos); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMasPeso, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMasPeso.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMenosPeso, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.lblMenosPeso.text")); // NOI18N

        txtMasPeso.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMasPeso.text")); // NOI18N
        txtMasPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMasPesoKeyTyped(evt);
            }
        });

        txtMenosPeso.setText(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.txtMenosPeso.text")); // NOI18N
        txtMenosPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMenosPesoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlAristasLayout = new javax.swing.GroupLayout(pnlAristas);
        pnlAristas.setLayout(pnlAristasLayout);
        pnlAristasLayout.setHorizontalGroup(
            pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAristasLayout.createSequentialGroup()
                        .addComponent(lblMenosPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(txtMenosPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAristasLayout.createSequentialGroup()
                        .addComponent(lblMasPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMasPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAristasLayout.setVerticalGroup(
            pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMasPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasPeso))
                .addGap(18, 18, 18)
                .addGroup(pnlAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenosPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenosPeso))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pnlFiltros.addTab(org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.pnlAristas.TabConstraints.tabTitle"), pnlAristas); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnFiltrar, org.openide.util.NbBundle.getMessage(OcvFilterUI.class, "OcvFilterUI.btnFiltrar.text")); // NOI18N
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFiltrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMasNodosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasNodosKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMasNodosKeyTyped

    private void txtMenosNodosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenosNodosKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMenosNodosKeyTyped

    private void txtMasComunidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasComunidadesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMasComunidadesKeyTyped

    private void txtMenosComunidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenosComunidadesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMenosComunidadesKeyTyped

    private void txtMasPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMasPesoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMasPesoKeyTyped

    private void txtMenosPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenosPesoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtMenosPesoKeyTyped

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JLabel lblConTags;
    private javax.swing.JLabel lblMasComunidades;
    private javax.swing.JLabel lblMasNodos;
    private javax.swing.JLabel lblMasPeso;
    private javax.swing.JLabel lblMenosComunidades;
    private javax.swing.JLabel lblMenosNodos;
    private javax.swing.JLabel lblMenosPeso;
    private javax.swing.JLabel lblSinTags;
    private javax.swing.JPanel pnlAristas;
    private javax.swing.JPanel pnlComunidades;
    private javax.swing.JTabbedPane pnlFiltros;
    private javax.swing.JPanel pnlNodos;
    private javax.swing.JTextField txtConTags;
    private javax.swing.JTextField txtMasComunidades;
    private javax.swing.JTextField txtMasNodos;
    private javax.swing.JTextField txtMasPeso;
    private javax.swing.JTextField txtMenosComunidades;
    private javax.swing.JTextField txtMenosNodos;
    private javax.swing.JTextField txtMenosPeso;
    private javax.swing.JTextField txtSinTags;
    // End of variables declaration//GEN-END:variables

}
